debug: true

spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: mcloud-config-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 10
      max-wait-millis: 200

server:
  port: 8001

mybatis:
  type-aliases-package: cn.xmut.mcloud.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  instance:
    instance-id: mcloud-config-dept-provider-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka


---
spring:
  profiles: test
  application:
    name: mcloud-config-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 10
      max-wait-millis: 200

server:
  port: 8001

mybatis:
  type-aliases-package: cn.xmut.mcloud.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  instance:
    instance-id: mcloud-config-dept-provider-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
